# Generated by Django 4.1.7 on 2023-03-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0002_user_alter_tweet_user_alter_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="user",),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default=True, max_length=10, unique=True),
        ),
    ]
