# Generated by Django 4.1.7 on 2023-03-12 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0003_remove_user_user_user_password_user_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet", old_name="user", new_name="username",
        ),
    ]
