# Generated by Django 4.1.7 on 2023-03-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0004_rename_user_tweet_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet", name="username", field=models.CharField(max_length=10),
        ),
    ]
