# Generated by Django 4.1.7 on 2023-03-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0005_alter_tweet_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mobile",
            field=models.CharField(default=True, max_length=10),
        ),
    ]
