# Generated by Django 4.1.7 on 2023-03-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0008_userprofile_mobile_delete_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.CharField(default=True, max_length=20),
        ),
    ]
